# Generated by Django 4.0.1 on 2022-01-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_allobjects_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='allobjects',
            name='workin_h',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allobjects',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
