# Generated by Django 4.0.1 on 2022-01-25 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_allobjects_workin_h_alter_allobjects_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allobjects',
            old_name='workin_h',
            new_name='working_h',
        ),
    ]
