# Generated by Django 4.0.1 on 2022-01-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_rename_workin_h_allobjects_working_h'),
    ]

    operations = [
        migrations.AddField(
            model_name='allobjects',
            name='map_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
