# Generated by Django 4.0.1 on 2022-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_allobjects_map_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allobjects',
            name='map_url',
        ),
        migrations.AddField(
            model_name='allobjects',
            name='lat',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allobjects',
            name='lng',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
