# Generated by Django 4.0.1 on 2022-01-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_remove_allobjects_map_url_allobjects_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allobjects',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
        migrations.AlterField(
            model_name='allobjects',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
    ]
