# Generated by Django 4.0.1 on 2022-01-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_alter_allobjects_lat_alter_allobjects_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allobjects',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='allobjects',
            name='lng',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
