# Generated by Django 4.0.1 on 2022-01-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctorprofile_objectob'),
        ('objects', '0009_alter_allobjects_lat_alter_allobjects_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='allobjects',
            name='doctors',
            field=models.ManyToManyField(to='doctors.DoctorProfile'),
        ),
    ]
