# Generated by Django 4.0.1 on 2022-01-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_allobjects_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allobjects',
            name='doctors',
        ),
    ]
