# Generated by Django 4.0.1 on 2022-01-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_allobjects_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allobjects',
            name='people',
        ),
        migrations.AddField(
            model_name='allobjects',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
