# Generated by Django 4.0.1 on 2022-01-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='object',
            new_name='objectOB',
        ),
    ]
