# Generated by Django 4.0.1 on 2022-01-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_object_doctorprofile_objectob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='objectOB',
        ),
    ]
