# Generated by Django 4.0.1 on 2022-01-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_remove_allobjects_doctors'),
        ('doctors', '0003_remove_doctorprofile_objectob'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctors',
            field=models.ManyToManyField(to='objects.AllObjects'),
        ),
    ]
