# Generated by Django 4.0.1 on 2022-01-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorprofile_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='doctors',
            new_name='work_place',
        ),
    ]
