# Generated by Django 4.0.1 on 2022-01-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_rename_doctors_doctorprofile_work_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='work_place',
        ),
    ]
