# Generated by Django 4.0.1 on 2022-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctorprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
