# Generated by Django 4.0.1 on 2022-01-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_remove_doctorprofile_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
