# Generated by Django 4.0.1 on 2022-01-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctorprofile_email_doctorprofile_phome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='phome',
            new_name='phone',
        ),
    ]
